name: Calculate CO2 🌱

on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Await CF Pages
        uses: WalshyDev/cf-pages-await@v1.0.1
        id: cf
        with:
          accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL }}
          apiKey: ${{ secrets.CF_API_KEY }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          project: ${{ secrets.CF_PROJECT_NAME }}
      - name: Calculate CO2 🌱
        uses: GeopJr/CO2@v1
        with:
          url: "${{ steps.cf.outputs.url }}"
          renewable: true